services:
    users-service:
        build:
            context: ./Backend
            dockerfile: users-service/Dockerfile
        ports:
            - "8081:8080"
            - "50051:50051"
        environment:
            - MONGO_DB_URI=mongodb://host.docker.internal:27017
            - PORT=8080
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            #- CONSUL_HTTP_ADDR=consul:8500  # Add Consul address to env
        networks:
            - app-network

    projects-service:
        build:
            context: ./Backend
            dockerfile: projects-service/Dockerfile
        ports:
            - "8082:8080"
        environment:
            - MONGO_DB_URI=mongodb://host.docker.internal:27017
            - PORT=8080
        networks:
            - app-network

    tasks-service:
        build: ./Backend/tasks-service
        ports:
            - "8083:8080"
        environment:
            - MONGO_DB_URI=mongodb://host.docker.internal:27017
            - PORT=8080
        networks:
            - app-network
        volumes:
            - ./Backend/tasks-service/.env:/app/.env
    
    notifications-service:
        build:
            context: ./Backend
            dockerfile: notifications-service/Dockerfile
        ports:
            - "8084:8080"
        env_file:
            - ./Backend/notifications-service/.env
        networks:
            - app-network
        
        environment:
            - PORT=8080
            # NoSQL: environment variable holding connection URI for Cassandra database
            - CASS_DB=cassandra:9042
            # NoSQL: Extremely important! Cassandra takes a lot of time to start!
            # If we don't wait for it to fully initialize we will get exceptions and will not be able to connect!

        depends_on:
            cassandra:
                condition: service_healthy

    cassandra:
        image: cassandra
        restart: always
        ports:
         - "9042:9042"
        # Docker healtcheck - checks if database is "alive"
        healthcheck:
            test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
            interval: 15s
            timeout: 5s
            retries: 30
        networks:
            - app-network

    api-gateway:
        build:
            context: ./Backend/api-gateway
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - USER_SERVICE=http://users-service:8080
            - PROJECT_SERVICE=http://projects-service:8080
            - TASK_SERVICE=http://tasks-service:8080
            - NOTIFICATION_SERVICE=http://notifications-service:8080
            - PORT=8080
        networks:
            - app-network
        volumes:
            - ./Backend/api-gateway/.env:/app/.env
        depends_on:
            - users-service
            - projects-service
            - tasks-service
            - notifications-service

    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        networks:
            - app-network

    # consul:
    #     image: "consul:1.14.2"
    #     ports:
    #         - "8500:8500"
    #     networks:
    #         - app-network
    #     command: "agent -dev -client=0.0.0.0"  # Run in dev mode to allow easy access
    
    frontend:
        build:
            context: ./Frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        env_file:
            - ./Frontend/.env
        networks:
            - app-network
        depends_on:
            - users-service
            - projects-service
            - tasks-service

networks:
    app-network:
        driver: bridge


volumes:
  cass_store: