# must be unique in a given SonarQube instance
sonar.projectKey=Trello-microservices

# --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=Backend,Frontend
 
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.go.coverage.reportPaths=coverage.out

# Personal/project-generated token from SonarQube
sonar.token=sqp_aef112d1755e6f7ae3264cd86bc2d71dbc460079

# SonarQube server URL
sonar.host.url=http://host.docker.internal:9001

sonar.exclusions=Backend/db/**


