syntax = "proto3";

package userservice;

option go_package = "pb/userpb";

// Service definition
service UserService {
    rpc GetAllUsers (GetAllUsersRequest) returns (GetAllUsersResponse);
    rpc CheckUserExistsByID (CheckUserExistsByIDRequest) returns (CheckUserExistsByIDResponse); // New function
}

// Request and response for GetAllUsers
message GetAllUsersRequest {}

message GetAllUsersResponse {
    repeated User users = 1;
}

// Request and response for CheckUserExistsByID
message CheckUserExistsByIDRequest {
    string user_id = 1; // User ID to check
}

message CheckUserExistsByIDResponse {
    bool exists = 1; // Whether the user exists or not
}

// User message representing a user object
message User {
    string id = 1;
    string first_name = 2;
    string last_name = 3;
    string password = 4;
    string email = 5;
    string username = 6;
    string role = 7;
}